version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: "${MYSQL_DATABASE_DATABASE}-container"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE_DATABASE}"
      MYSQL_USER: "${MYSQL_DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_DATABASE_PASSWORD}"
    ports:
      - "${MYSQL_DATABASE_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
