const resumeAstTemplate = {
  uuid: "f10d71e7-60c0-46df-8b78-d214169e3bda",
  type: "div",
  events: {},
  props: {
    className: "",
    style: {
      width: "100%",
      minHeight: "100%",
      display: "block",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 1)",
      position: "relative",
      paddingTop: "",
      paddingRight: "",
      paddingLeft: "",
    },
    attributes: { datanodetype: "" },
  },
  children: [
    {
      uuid: "22329ee4-1acf-4ee7-9aae-360f783f1f05",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "150px",
          display: "flex",
          flexDirection: "row",
          justifyContent: "space-between",
          alignItems: "center",
          color: "rgba(255, 255, 255, 1)",
          backgroundColor: "rgba(52, 56, 77, 1)",
          boxShadow: "0 0 #000000",
          paddingRight: "20px",
          paddingLeft: "20px",
          marginBottom: "54px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "9c4b45b2-d98b-4e81-a0b9-b23b64702b50",
          parent: "22329ee4-1acf-4ee7-9aae-360f783f1f05",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "150px",
              height: "auto",
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              backgroundColor: "rgba(255, 255, 255, 21274374391337924)",
              position: "absolute",
              top: "52px",
              paddingTop: "2px",
              paddingRight: "2px",
              paddingBottom: "2px",
              paddingLeft: "2px",
              marginRight: "10%",
              borderTopLeftRadius: "50%",
              borderTopRightRadius: "50%",
              borderBottomLeftRadius: "50%",
              borderBottomRightRadius: "50%",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "1043861d-969b-49e9-9d2d-82310b67d269",
              parent: "9c4b45b2-d98b-4e81-a0b9-b23b64702b50",
              type: "img",
              events: {},
              props: {
                className: "",
                style: {
                  width: "150px",
                  height: "auto",
                  backgroundColor: "rgba(255, 255, 255, 21274374391337924)",
                  borderStyle: "solid",
                  borderColor: "rgba(137, 137, 137, 1)",
                  borderTopWidth: "1px",
                  borderBottomWidth: "1px",
                  borderLeftWidth: "1px",
                  borderRightWidth: "1px",
                  borderTopLeftRadius: "50%",
                  borderTopRightRadius: "50%",
                  borderBottomLeftRadius: "50%",
                  borderBottomRightRadius: "50%",
                },
                attributes: {
                  datanodetype: "",
                  src: "https://zebra-central-incredibly.ngrok-free.app/api/public/uploads/5709409b-b952-434e-8016-f89aa74e11f6.jpg",
                  alt: "1043861d-969b-49e9-9d2d-82310b67d269",
                  crossOrigin: "anonymous",
                },
              },
              children: [],
              content: "",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "4048c134-eb1e-40eb-afc1-75f63c4ecc9f",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "ca527fd2-744e-44ff-ba7c-aec413cc8a5d",
          parent: "4048c134-eb1e-40eb-afc1-75f63c4ecc9f",
          type: "span",
          events: {},
          props: {
            className: "",
            style: {
              display: "block",
              fontSize: "24px",
              fontWeight: "bolder",
              paddingBottom: "10px",
              marginBottom: "15px",
              borderStyle: "solid",
              borderColor: "rgba(0, 0, 0, 1)",
              borderTopWidth: "0px",
              borderBottomWidth: "1px",
              borderLeftWidth: "0px",
              borderRightWidth: "0px",
            },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "基本資料",
        },
        {
          uuid: "6216e6e1-5e23-4cdf-a239-1d6cd0d36913",
          parent: "4048c134-eb1e-40eb-afc1-75f63c4ecc9f",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "auto",
              height: "auto",
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              paddingRight: "10px",
              paddingLeft: "10px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "25bd23b2-8c38-4ad1-adde-bddeb3e835e7",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "auto",
                  height: "auto",
                  display: "flex",
                  flexGrow: "0.8",
                  flexDirection: "row",
                  justifyContent: "end",
                  alignItems: "end",
                  paddingBottom: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "",
            },
            {
              uuid: "a49b460b-53df-4ece-8fbf-59d4ccd4c9d5",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "100%",
                  height: "auto",
                  display: "flex",
                  flexGrow: "0.4",
                  flexDirection: "column",
                  justifyContent: "start",
                  alignItems: "end",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "f767e0d6-6848-4564-ad41-882f18605d6e",
                  parent: "a49b460b-53df-4ece-8fbf-59d4ccd4c9d5",
                  type: "div",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      width: "100%",
                      display: "flex",
                      flexDirection: "row",
                      justifyContent: "space-between",
                      alignItems: "space-around",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [
                    {
                      uuid: "067a2de3-1ffb-4cbb-8594-0a49b54c8cf7",
                      parent: "f767e0d6-6848-4564-ad41-882f18605d6e",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: { display: "block" },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "姓名:",
                    },
                    {
                      uuid: "7640892b-4a6e-4d1c-b24c-aac2cf98c404",
                      parent: "f767e0d6-6848-4564-ad41-882f18605d6e",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: {
                          display: "block",
                          textAlign: "right",
                        },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "林奕愷 JackyLin",
                    },
                  ],
                  content: "",
                },
                {
                  uuid: "aeaa6a3b-dafd-4ea7-aa8f-ed75a9931f47",
                  parent: "a49b460b-53df-4ece-8fbf-59d4ccd4c9d5",
                  type: "div",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      width: "100%",
                      display: "flex",
                      flexDirection: "row",
                      justifyContent: "space-between",
                      alignItems: "space-around",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [
                    {
                      uuid: "374dbef7-7157-40e8-a8db-bdd45a8c7f3b",
                      parent: "aeaa6a3b-dafd-4ea7-aa8f-ed75a9931f47",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: { display: "block" },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "手機:",
                    },
                    {
                      uuid: "af2fde74-73cf-44a2-80d0-3feada3157bc",
                      parent: "aeaa6a3b-dafd-4ea7-aa8f-ed75a9931f47",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: {
                          display: "block",
                          textAlign: "right",
                        },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "+886958-239-930",
                    },
                  ],
                  content: "",
                },
                {
                  uuid: "a272bbd1-dd9d-4087-aea5-ab4e81547fb3",
                  parent: "a49b460b-53df-4ece-8fbf-59d4ccd4c9d5",
                  type: "div",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      width: "100%",
                      display: "flex",
                      flexDirection: "row",
                      justifyContent: "space-between",
                      alignItems: "space-around",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [
                    {
                      uuid: "58d6a42b-05c2-4ed0-8602-27b455c5f461",
                      parent: "a272bbd1-dd9d-4087-aea5-ab4e81547fb3",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: { display: "block" },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "生日:",
                    },
                    {
                      uuid: "ed449d9a-e667-464e-8aab-e24aed7b7ce2",
                      parent: "a272bbd1-dd9d-4087-aea5-ab4e81547fb3",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: {
                          display: "block",
                          textAlign: "right",
                        },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "1992/09/30",
                    },
                  ],
                  content: "",
                },
                {
                  uuid: "b7461682-f0cd-4e34-a7dc-560e01394f6c",
                  parent: "a49b460b-53df-4ece-8fbf-59d4ccd4c9d5",
                  type: "div",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      width: "100%",
                      display: "flex",
                      flexDirection: "row",
                      justifyContent: "space-between",
                      alignItems: "space-around",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [
                    {
                      uuid: "4dfd077e-0974-45fc-9365-b7788949003a",
                      parent: "b7461682-f0cd-4e34-a7dc-560e01394f6c",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: { display: "block" },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "github: ",
                    },
                    {
                      uuid: "066bb5af-1a6c-4657-a431-f3cd06cb2e71",
                      parent: "b7461682-f0cd-4e34-a7dc-560e01394f6c",
                      type: "span",
                      events: {},
                      props: {
                        className: "",
                        style: {
                          display: "block",
                          textAlign: "right",
                        },
                        attributes: { datanodetype: "" },
                      },
                      children: [],
                      content: "https://github.com/jasonlinkai",
                    },
                  ],
                  content: "",
                },
              ],
              content: "",
            },
            {
              uuid: "22fa2f02-d195-44c8-b979-bee09154c1c6",
              parent: "6216e6e1-5e23-4cdf-a239-1d6cd0d36913",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "100%",
                  display: "flex",
                  flexDirection: "row",
                  justifyContent: "space-between",
                  alignItems: "space-around",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "55a4ff85-d70b-4e19-9ac5-f1b5fdeac341",
                  parent: "22fa2f02-d195-44c8-b979-bee09154c1c6",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "信箱:",
                },
                {
                  uuid: "68838b94-0aa2-4228-9c01-778f5fc0a8a8",
                  parent: "22fa2f02-d195-44c8-b979-bee09154c1c6",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", textAlign: "right" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "loveguitar668@gmail.com",
                },
              ],
              content: "",
            },
            {
              uuid: "0d7a69d3-1d08-4022-a1a4-273b03c3febf",
              parent: "6216e6e1-5e23-4cdf-a239-1d6cd0d36913",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "100%",
                  display: "flex",
                  flexDirection: "row",
                  justifyContent: "space-between",
                  alignItems: "space-around",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "87e04566-c6b5-420f-9a9d-d50c6997c11a",
                  parent: "0d7a69d3-1d08-4022-a1a4-273b03c3febf",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "Web Design IDE:",
                },
                {
                  uuid: "eda2d20e-76d4-41d1-99f0-4509e4d670c0",
                  parent: "0d7a69d3-1d08-4022-a1a4-273b03c3febf",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", textAlign: "right" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content:
                    "https://zebra-central-incredibly.ngrok-free.app/backend/login",
                },
              ],
              content: "",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "9152588a-6ffa-4390-b960-0a74ffab409a",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: {
              display: "block",
              fontSize: "24px",
              fontWeight: "bolder",
              paddingBottom: "10px",
              marginBottom: "15px",
              borderStyle: "solid",
              borderColor: "rgba(0, 0, 0, 1)",
              borderTopWidth: "0px",
              borderBottomWidth: "1px",
              borderLeftWidth: "0px",
              borderRightWidth: "0px",
            },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "自傳",
        },
        {
          uuid: "982f4eb5-071c-4edd-935a-65eb6719b79f",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "您好，我是Jacky。",
        },
        {
          uuid: "fa2ae5e2-443d-4d07-a113-9ddb0a47148f",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "目前您所看見的履歷是使用我自建的網頁設計視覺化IDE所建立。",
        },
        {
          uuid: "447178a7-89f8-4f66-a03a-be708a3b48f7",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content:
            "如有興趣可以訪問(https://zebra-central-incredibly.ngrok-free.app/backend/login)。",
        },
        {
          uuid: "58a07112-0010-4ed7-80ac-449f64b1f649",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content:
            "個性認真、負責、好奇、追根究底。  透過上網自學，轉職前端工程師，擁有強大的自學能力。",
        },
        {
          uuid: "27897cc8-4c0f-43c4-be8f-6322369537f5",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content:
            "軟體開發經驗6年，善於與同事進行溝通，熟悉前端JS及衍伸之各種開發工具。",
        },
        {
          uuid: "c72e74a9-224c-4a08-b1e3-b742a9eaa422",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content:
            "夠熟稔的使用Git進行多人協作、版本控制，了解基本的Linux操作指令。",
        },
        {
          uuid: "e0fa3d13-700c-40df-b314-fdcce5356469",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", marginBottom: "10px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content:
            "個性認真、負責、好奇、追根究底。  透過上網自學，轉職前端工程師，擁有強大的自學能力。",
        },
        {
          uuid: "614fb2ec-fbf3-4023-8092-c35a48127dbe",
          parent: "b9142ca6-ed9d-4eb7-bec5-e5bd3aeebcf2",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content:
            "也在AWS上建立簡單的CI、CD容器化部落格基於Next.js，這是我目前的學習路徑。",
        },
      ],
      content: "",
    },
    {
      uuid: "5bf959fa-e78f-4301-9f79-2aa3ed4b4368",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "b365e086-08ad-4a4e-a64e-5cf2508c3ecd",
          parent: "5bf959fa-e78f-4301-9f79-2aa3ed4b4368",
          type: "span",
          events: {},
          props: {
            className: "",
            style: {
              display: "block",
              fontSize: "24px",
              fontWeight: "bolder",
              paddingBottom: "10px",
              marginBottom: "15px",
              borderStyle: "solid",
              borderColor: "rgba(0, 0, 0, 1)",
              borderTopWidth: "0px",
              borderBottomWidth: "1px",
              borderLeftWidth: "0px",
              borderRightWidth: "0px",
            },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "學歷",
        },
        {
          uuid: "6c58fbb0-a4cf-4b79-b48c-76b3fea9239f",
          parent: "5bf959fa-e78f-4301-9f79-2aa3ed4b4368",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "13f4257d-d337-446f-827b-80b2ccd18453",
              parent: "6c58fbb0-a4cf-4b79-b48c-76b3fea9239f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontSize: "20px",
                  fontWeight: "bold",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "世新大學",
            },
            {
              uuid: "9131fd2c-16e6-438d-b702-8eab559edd9d",
              parent: "6c58fbb0-a4cf-4b79-b48c-76b3fea9239f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", textAlign: "center" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "觀光餐旅管理組 學士",
            },
            {
              uuid: "614aaf0e-bee2-432c-935a-4f26c8ad63fe",
              parent: "6c58fbb0-a4cf-4b79-b48c-76b3fea9239f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(124, 124, 124, 1)",
                  textAlign: "right",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "2012-09 ~ 2016-03",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "96ec9b47-996f-4db4-b4d8-c0be7f59ed6e",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "6e922726-c14a-4e43-b33d-6e0a864d9e91",
          parent: "96ec9b47-996f-4db4-b4d8-c0be7f59ed6e",
          type: "span",
          events: {},
          props: {
            className: "",
            style: {
              display: "block",
              fontSize: "24px",
              fontWeight: "bolder",
              paddingBottom: "10px",
              marginBottom: "15px",
              borderStyle: "solid",
              borderColor: "rgba(0, 0, 0, 1)",
              borderTopWidth: "0px",
              borderBottomWidth: "1px",
              borderLeftWidth: "0px",
              borderRightWidth: "0px",
            },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "技能",
        },
        {
          uuid: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
          parent: "96ec9b47-996f-4db4-b4d8-c0be7f59ed6e",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "flex",
              flexWrap: "wrap",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "start",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "f757b366-7f47-4575-9a30-fa8b4290f7ef",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "aebd3bb1-770e-4c2f-81de-2f6e652e5234",
                  parent: "f757b366-7f47-4575-9a30-fa8b4290f7ef",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "ReactNative",
                },
                {
                  uuid: "090b7166-fe72-443a-932f-bc49f3d69198",
                  parent: "f757b366-7f47-4575-9a30-fa8b4290f7ef",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2019 ~ 熟悉",
                },
              ],
              content: "",
            },
            {
              uuid: "0dfe9ce3-3aad-4ec3-859b-54946751fa35",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "9b851c59-6638-4c24-b401-071db97c363c",
                  parent: "0dfe9ce3-3aad-4ec3-859b-54946751fa35",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "React",
                },
                {
                  uuid: "36e697a7-9e4e-436b-b9cd-d14cfdf77b21",
                  parent: "0dfe9ce3-3aad-4ec3-859b-54946751fa35",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2019 ~ 精通",
                },
              ],
              content: "",
            },
            {
              uuid: "030a8fb5-f581-4ec7-8529-866d404e66db",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "886e24ee-793d-44f6-9cf7-a71ee59f1848",
                  parent: "030a8fb5-f581-4ec7-8529-866d404e66db",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "Cocos2d.js",
                },
                {
                  uuid: "0a770336-ee90-42ef-9b78-064a0ced7915",
                  parent: "030a8fb5-f581-4ec7-8529-866d404e66db",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2019 ~ 普通",
                },
              ],
              content: "",
            },
            {
              uuid: "dc475439-956a-44e0-a691-bf9685856d79",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "67238224-2e9e-462e-9571-95d5221a91d5",
                  parent: "dc475439-956a-44e0-a691-bf9685856d79",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "Vue2",
                },
                {
                  uuid: "5b431b3d-e56c-47f9-82de-05bcb1eccc3b",
                  parent: "dc475439-956a-44e0-a691-bf9685856d79",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2018 ~ 熟悉",
                },
              ],
              content: "",
            },
            {
              uuid: "e83ec1cf-fb42-4af7-8ece-5a2025698d9c",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "7822c64f-2597-47b1-b632-4bd87873176e",
                  parent: "e83ec1cf-fb42-4af7-8ece-5a2025698d9c",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "Angular.js",
                },
                {
                  uuid: "0367d918-948c-4590-a03b-284829e9cdae",
                  parent: "e83ec1cf-fb42-4af7-8ece-5a2025698d9c",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2018 ~ 普通",
                },
              ],
              content: "",
            },
            {
              uuid: "7ba40b26-2b34-40b4-903c-0edb8b5c2fc9",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "96f6b8ee-31f0-4b25-b173-d3553207db57",
                  parent: "7ba40b26-2b34-40b4-903c-0edb8b5c2fc9",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "Typescript",
                },
                {
                  uuid: "7e5aa545-010e-44b0-983b-296aee9f11ca",
                  parent: "7ba40b26-2b34-40b4-903c-0edb8b5c2fc9",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2022-03 ~ 熟悉",
                },
              ],
              content: "",
            },
            {
              uuid: "7f0efda6-d0fe-4ea8-afdd-8d55715db198",
              parent: "c0d92090-f911-4f22-9a07-052b4dcf7f1b",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "300px",
                  display: "flex",
                  flexBasis: "30%",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  alignItems: "center",
                  boxShadow: "2px 2px 2px 1px #696969ff",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "513152e5-49a1-4551-b4fe-97154210715f",
                  parent: "7f0efda6-d0fe-4ea8-afdd-8d55715db198",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontWeight: "bold" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "JavaScript",
                },
                {
                  uuid: "8bcb0626-6757-423e-b4b9-233658c935c6",
                  parent: "7f0efda6-d0fe-4ea8-afdd-8d55715db198",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "12px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2018 ~ 精通",
                },
              ],
              content: "",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "a556a3f6-ca74-49b4-988c-09ec62e8d26a",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "251b17a0-4e94-494a-8eb8-b02ce477d8ef",
          parent: "a556a3f6-ca74-49b4-988c-09ec62e8d26a",
          type: "span",
          events: {},
          props: {
            className: "",
            style: {
              display: "block",
              fontSize: "24px",
              fontWeight: "bolder",
              paddingBottom: "10px",
              marginBottom: "15px",
              borderStyle: "solid",
              borderColor: "rgba(0, 0, 0, 1)",
              borderTopWidth: "0px",
              borderBottomWidth: "1px",
              borderLeftWidth: "0px",
              borderRightWidth: "0px",
            },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "經歷",
        },
        {
          uuid: "b54c6121-80d2-45b1-852a-286b54ce7011",
          parent: "a556a3f6-ca74-49b4-988c-09ec62e8d26a",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "8dcdf3b8-cd8c-434b-8a9a-3adfff57237d",
              parent: "b54c6121-80d2-45b1-852a-286b54ce7011",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(0, 0, 0, 1)",
                  fontSize: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "2022-03 ~ 2024-03",
            },
            {
              uuid: "30b26be6-0054-4e85-bd60-2917b0af493f",
              parent: "b54c6121-80d2-45b1-852a-286b54ce7011",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", fontSize: "20px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "米约科技有限公司",
            },
            {
              uuid: "77afb26e-1930-42f8-84c5-a50cc740b895",
              parent: "b54c6121-80d2-45b1-852a-286b54ce7011",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(0, 0, 0, 1)",
                  fontSize: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "資深前端工程師",
            },
          ],
          content: "",
        },
        {
          uuid: "17ab60bd-f8dc-4143-a796-b248720cae4c",
          parent: "a556a3f6-ca74-49b4-988c-09ec62e8d26a",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "65f1cb25-a8ab-42fa-82c0-5eb763c5a874",
              parent: "17ab60bd-f8dc-4143-a796-b248720cae4c",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontWeight: "bold",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "西瓜棋牌",
            },
            {
              uuid: "d77e45a4-57dc-4243-8c02-702831b85896",
              parent: "17ab60bd-f8dc-4143-a796-b248720cae4c",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・開發共用部分(ex: 全局音效控制、全局彈窗、TABLE元件...)",
            },
            {
              uuid: "51f8dfe2-1404-4dff-b50a-18a9af0279a7",
              parent: "17ab60bd-f8dc-4143-a796-b248720cae4c",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・使用Webpack實現Web版本配適",
            },
            {
              uuid: "8f95a4c4-e11b-43b2-b75a-c3f9b75730a7",
              parent: "17ab60bd-f8dc-4143-a796-b248720cae4c",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・導入圖片預載、Webp圖片格式，減少包體大小及渲染速度",
            },
            {
              uuid: "92773aee-95d6-432e-abba-257e2ffb1daf",
              parent: "17ab60bd-f8dc-4143-a796-b248720cae4c",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・串接APM、渠道統計，上報錯誤訊息，降低bug查找難度，並進行推廣資料收集",
            },
            {
              uuid: "dffd1e68-9e53-4af0-8883-82b16ce63b7a",
              parent: "17ab60bd-f8dc-4143-a796-b248720cae4c",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・導入patch-package修復依賴模組，降低使用外部模組的維護成本",
            },
          ],
          content: "",
        },
        {
          uuid: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
          parent: "a556a3f6-ca74-49b4-988c-09ec62e8d26a",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "3a1a102b-20ce-498e-8ad7-3755184e5019",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontWeight: "bold",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "喜鵲聊天",
            },
            {
              uuid: "c00424e5-0aa9-4743-865c-f2ba3ed7e6c6",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・開發軟件主要功能(ex: 語音、圖片、影片、檔案上傳、離線推播、強熱更新...)",
            },
            {
              uuid: "33ce4c14-3b51-434a-ab2a-b3c21eeabf9b",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・基於WebSocket實現即時通訊，實作ACK機制確保消息接收",
            },
            {
              uuid: "a16371cd-b3e4-4c2a-aba2-56aaa2a57bdd",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・導入圖片預載、Webp圖片格式，減少包體大小及渲染速度",
            },
            {
              uuid: "bb94c59d-ec3c-4f05-a1d1-652a8e2b021c",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・批量處理訊息，減少JS與原生層的溝通次數，進而提高畫面流暢度",
            },
            {
              uuid: "d0ef2c28-75ce-4348-8663-81fb3a76ef55",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・開發打包腳本、建置M1打包機，降低運維人員自動化打包APP成本",
            },
            {
              uuid: "7f05265f-64ed-4856-9945-11df1aaf999e",
              parent: "04f5c662-1e99-4d80-b83c-98d75d0ee08a",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・將APP上架至AppStore及GooglePlay",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "0e7338ae-289c-4d63-881b-c13433d85f67",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "a1235064-facf-4fa4-a9dd-87bed8fa7ed7",
          parent: "0e7338ae-289c-4d63-881b-c13433d85f67",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "c9b5f76a-acb8-4a11-b3d9-ad28ffbfdf69",
              parent: "a1235064-facf-4fa4-a9dd-87bed8fa7ed7",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(0, 0, 0, 1)",
                  fontSize: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "2021-03 ~ 2022-03",
            },
            {
              uuid: "bc318733-c109-4524-b7cf-e5274e16b843",
              parent: "a1235064-facf-4fa4-a9dd-87bed8fa7ed7",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", fontSize: "20px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "怡和科技有限公司",
            },
            {
              uuid: "930002e0-1210-4108-83cd-8716ed349e14",
              parent: "a1235064-facf-4fa4-a9dd-87bed8fa7ed7",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(0, 0, 0, 1)",
                  fontSize: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "資深前端工程師",
            },
          ],
          content: "",
        },
        {
          uuid: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
          parent: "0e7338ae-289c-4d63-881b-c13433d85f67",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "d882c68a-6267-434d-90c3-59bbde371603",
              parent: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontWeight: "bold",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "多商戶架構之彩票遊戲前台及其Headless CMS後台",
            },
            {
              uuid: "68cfa4bc-1f3d-4183-a07f-7a82ca633dc6",
              parent: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・架構開發前後台前端專案",
            },
            {
              uuid: "1577a34b-5102-4b93-bb68-ec9301e26726",
              parent: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・使用Webpack的Alias功能實現編譯時換皮",
            },
            {
              uuid: "94dde35b-1307-4a27-8bdc-d9f3cab69c28",
              parent: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・使用i18n開發多國語系版本",
            },
            {
              uuid: "dc660a84-466a-49a8-9984-057c8d6860ba",
              parent: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・帶領美術人員依照專案規範進行切版",
            },
            {
              uuid: "652c5bc4-e2a1-4235-8b2d-01a24f85d07f",
              parent: "61ed69da-22bf-4f85-ba3a-0bca14c2b058",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・與美術人員、產品經理、後端工程師溝通及討論迭代產品功能",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "0e2e4bb1-9cd9-4bf3-8ab3-6aa7704d58a4",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "300px",
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "97e9839f-fe50-4b51-a55b-0e0dd350f6e6",
          parent: "0e2e4bb1-9cd9-4bf3-8ab3-6aa7704d58a4",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "20px",
              paddingRight: "20px",
              paddingBottom: "20px",
              paddingLeft: "20px",
              marginBottom: "20px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "19ad8e79-efa0-4d05-a9a3-26fe447e0372",
              parent: "97e9839f-fe50-4b51-a55b-0e0dd350f6e6",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "100%",
                  display: "flex",
                  flexDirection: "row",
                  justifyContent: "space-between",
                  alignItems: "center",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "9c2bf69f-d8d4-4fee-949b-e21797511985",
                  parent: "19ad8e79-efa0-4d05-a9a3-26fe447e0372",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      color: "rgba(0, 0, 0, 1)",
                      fontSize: "20px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "2020-03 ~ 2021-03",
                },
                {
                  uuid: "f11fa4d8-ac19-4b55-8e63-939d622c0093",
                  parent: "19ad8e79-efa0-4d05-a9a3-26fe447e0372",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: { display: "block", fontSize: "20px" },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "華澳科技有限公司",
                },
                {
                  uuid: "5e1b5fb6-6d96-470b-8314-86d1d0f80c6c",
                  parent: "19ad8e79-efa0-4d05-a9a3-26fe447e0372",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      color: "rgba(0, 0, 0, 1)",
                      fontSize: "20px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "中階前端工程師",
                },
              ],
              content: "",
            },
            {
              uuid: "134fe18f-3ea5-4542-ad8b-41b6b4bd9114",
              parent: "97e9839f-fe50-4b51-a55b-0e0dd350f6e6",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "100%",
                  height: "auto",
                  display: "block",
                  flexDirection: "row",
                  justifyContent: "center",
                  alignItems: "center",
                  paddingTop: "15px",
                  paddingBottom: "15px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "62233d7b-36af-4a01-acdd-8274b10acd55",
                  parent: "134fe18f-3ea5-4542-ad8b-41b6b4bd9114",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      fontWeight: "bold",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "Web彩票遊戲前後台",
                },
                {
                  uuid: "2e960556-0a99-4a30-bc2f-3c70f666e436",
                  parent: "134fe18f-3ea5-4542-ad8b-41b6b4bd9114",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "・值班OnCall解決線上緊急問題",
                },
                {
                  uuid: "b50317d9-c7e4-440e-af08-549875244bad",
                  parent: "134fe18f-3ea5-4542-ad8b-41b6b4bd9114",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "・共用邏輯模組開發設計維護",
                },
                {
                  uuid: "0716a15f-af12-4a82-bc0b-728c894ad448",
                  parent: "134fe18f-3ea5-4542-ad8b-41b6b4bd9114",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "・依照Zeplin圖稿進行切版及功能開發",
                },
              ],
              content: "",
            },
            {
              uuid: "6fc78199-fb8c-4525-83a7-aa348a6e27ea",
              parent: "97e9839f-fe50-4b51-a55b-0e0dd350f6e6",
              type: "div",
              events: {},
              props: {
                className: "",
                style: {
                  width: "100%",
                  height: "auto",
                  display: "block",
                  flexDirection: "row",
                  justifyContent: "center",
                  alignItems: "center",
                  paddingTop: "15px",
                  paddingBottom: "15px",
                },
                attributes: { datanodetype: "" },
              },
              children: [
                {
                  uuid: "19ba981a-79c3-4d30-87a3-071291baacad",
                  parent: "6fc78199-fb8c-4525-83a7-aa348a6e27ea",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      fontWeight: "bold",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "WebViewApp開發維護",
                },
                {
                  uuid: "b3e09b00-b4c3-41e4-bf2d-0e4a9e411373",
                  parent: "6fc78199-fb8c-4525-83a7-aa348a6e27ea",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "・建置RN打包機，建立Jenkins提供給運維人員使用",
                },
                {
                  uuid: "15e1ce7f-bac2-4757-a0cf-ee2dbd9e7940",
                  parent: "6fc78199-fb8c-4525-83a7-aa348a6e27ea",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "・浮動操作介面功能開發",
                },
                {
                  uuid: "94d05906-2ac7-4c6e-bdb4-1a81dc8ebdab",
                  parent: "6fc78199-fb8c-4525-83a7-aa348a6e27ea",
                  type: "span",
                  events: {},
                  props: {
                    className: "",
                    style: {
                      display: "block",
                      marginBottom: "10px",
                    },
                    attributes: { datanodetype: "" },
                  },
                  children: [],
                  content: "・使用PostMessage讓APP及WEB建立雙端溝通介面",
                },
              ],
              content: "",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "4c386d15-8c01-4b93-aed3-fef0d44995c2",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "auto",
          display: "block",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          paddingTop: "20px",
          paddingRight: "20px",
          paddingBottom: "20px",
          paddingLeft: "20px",
          marginBottom: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "9b5e4269-dfb3-4cc2-8c27-c902128075b3",
          parent: "4c386d15-8c01-4b93-aed3-fef0d44995c2",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "07a1e4bd-774d-4f94-846c-b5aec0ba30ae",
              parent: "9b5e4269-dfb3-4cc2-8c27-c902128075b3",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(0, 0, 0, 1)",
                  fontSize: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "2018-04 ~ 2020-03",
            },
            {
              uuid: "31770925-8e21-4619-b9a2-a6a6ae904da3",
              parent: "9b5e4269-dfb3-4cc2-8c27-c902128075b3",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", fontSize: "20px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "金貝科技有限公司",
            },
            {
              uuid: "06a06ee2-bf6a-44ba-bc0c-aab300eef3e3",
              parent: "9b5e4269-dfb3-4cc2-8c27-c902128075b3",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  color: "rgba(0, 0, 0, 1)",
                  fontSize: "20px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "初階前端工程師",
            },
          ],
          content: "",
        },
        {
          uuid: "71310821-0bd0-4dec-adf3-c0649278106f",
          parent: "4c386d15-8c01-4b93-aed3-fef0d44995c2",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "e8135cda-b816-4459-bced-308a570e2f9c",
              parent: "71310821-0bd0-4dec-adf3-c0649278106f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontWeight: "bold",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "彩票遊戲H5/APP",
            },
            {
              uuid: "e3052d7b-5fe9-4dd8-a723-4346014365d7",
              parent: "71310821-0bd0-4dec-adf3-c0649278106f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・前台功能開發(ex: 登入、註冊、公告、活動、會員中心...等等)",
            },
            {
              uuid: "b7deb136-88af-4bd1-8c4a-a053a9a311a2",
              parent: "71310821-0bd0-4dec-adf3-c0649278106f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・前端表單共用控件開發",
            },
            {
              uuid: "3e349878-0ddd-4bf2-94d1-4f069a100df2",
              parent: "71310821-0bd0-4dec-adf3-c0649278106f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・開發基於Websocket聊天系統",
            },
            {
              uuid: "38e93b87-b68c-4452-ab5c-64d35a7a2343",
              parent: "71310821-0bd0-4dec-adf3-c0649278106f",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・指導網頁設計師在專案中依照規範進行切版",
            },
          ],
          content: "",
        },
        {
          uuid: "aad7566b-1c23-4382-8c77-8f9bf183fe23",
          parent: "4c386d15-8c01-4b93-aed3-fef0d44995c2",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "8f529a64-557c-4a3d-99c0-58c4016fc47b",
              parent: "aad7566b-1c23-4382-8c77-8f9bf183fe23",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontWeight: "bold",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "彩票遊戲Headless CMS主客戶後台",
            },
            {
              uuid: "b37dd1b8-38b9-4945-8c85-4f3b70725543",
              parent: "aad7566b-1c23-4382-8c77-8f9bf183fe23",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・參考AngularJS專案進行Vue版的重構作業",
            },
            {
              uuid: "1ec758d2-3a29-4d0e-8125-316257fcc26e",
              parent: "aad7566b-1c23-4382-8c77-8f9bf183fe23",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・各項前台內容相關設置功能開發",
            },
            {
              uuid: "9ea7d3c3-cc47-4508-a126-c16036ecb03c",
              parent: "aad7566b-1c23-4382-8c77-8f9bf183fe23",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content:
                "・使用Cypress實作end-to-end testing測試用例，確保重構無誤",
            },
          ],
          content: "",
        },
        {
          uuid: "c73e7d76-151d-483e-91a0-a1368f215b52",
          parent: "4c386d15-8c01-4b93-aed3-fef0d44995c2",
          type: "div",
          events: {},
          props: {
            className: "",
            style: {
              width: "100%",
              height: "auto",
              display: "block",
              flexDirection: "row",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
            attributes: { datanodetype: "" },
          },
          children: [
            {
              uuid: "c83b9820-99b5-444d-a4a0-a3f4d76d18d5",
              parent: "c73e7d76-151d-483e-91a0-a1368f215b52",
              type: "span",
              events: {},
              props: {
                className: "",
                style: {
                  display: "block",
                  fontWeight: "bold",
                  marginBottom: "10px",
                },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "招財貓棋牌APP",
            },
            {
              uuid: "70e32ac9-f8a6-4159-92e6-9a5f28361828",
              parent: "c73e7d76-151d-483e-91a0-a1368f215b52",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・研究專案基於Cocos2d-js之可行性及遊戲開發邏輯學習",
            },
            {
              uuid: "cd52811a-c114-425c-8286-40ac93d0d983",
              parent: "c73e7d76-151d-483e-91a0-a1368f215b52",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・專案JS邏輯架構制定",
            },
            {
              uuid: "9b3b1a90-edbf-47aa-b4c5-e08583279e96",
              parent: "c73e7d76-151d-483e-91a0-a1368f215b52",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・導入既有後端API相關邏輯",
            },
            {
              uuid: "82ae713d-56bb-4c45-90ae-11c8d5541bff",
              parent: "c73e7d76-151d-483e-91a0-a1368f215b52",
              type: "span",
              events: {},
              props: {
                className: "",
                style: { display: "block", marginBottom: "10px" },
                attributes: { datanodetype: "" },
              },
              children: [],
              content: "・帶領動畫人員開發並維護項目主要功能",
            },
          ],
          content: "",
        },
      ],
      content: "",
    },
    {
      uuid: "68837c4a-27a7-41fe-900b-f2c44e03c358",
      parent: "f10d71e7-60c0-46df-8b78-d214169e3bda",
      type: "div",
      events: {},
      props: {
        className: "",
        style: {
          width: "100%",
          height: "150px",
          display: "flex",
          flexDirection: "row",
          justifyContent: "center",
          alignItems: "center",
          color: "rgba(255, 255, 255, 1)",
          backgroundColor: "rgba(52, 56, 77, 1)",
          boxShadow: "0 0 #000000",
          paddingRight: "20px",
          paddingLeft: "20px",
        },
        attributes: { datanodetype: "" },
      },
      children: [
        {
          uuid: "a66710b9-2b8c-4c58-bcba-fef0a8b3e707",
          parent: "68837c4a-27a7-41fe-900b-f2c44e03c358",
          type: "span",
          events: {},
          props: {
            className: "",
            style: { display: "block", fontSize: "20px" },
            attributes: { datanodetype: "" },
          },
          children: [],
          content: "Powered by web-editor.js.",
        },
      ],
      content: "",
    },
  ],
  content: "",
};

export const pageTemplateMap = {
  resume: {
    uuid: "ed270312-4088-4e09-9f46-161c8efcaa03",
    title: "resume-template",
    ast: resumeAstTemplate,
  },
};

export const pageTemplates = [pageTemplateMap.resume];
