const options = {
  display: [
    { label: "not selected", value: "" },
    { label: "block", value: "block" },
    { label: "flex", value: "flex" },
    { label: "inline", value: "inline" },
    { label: "none", value: "none" },
  ],
  flexWrap: [
    { label: "not selected", value: "" },
    { label: "nowrap", value: "nowrap" },
    { label: "wrap", value: "wrap" },
    { label: "wrap-reverse", value: "wrap-reverse" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
  flexDirection: [
    { label: "not selected", value: "" },
    { label: "row", value: "row" },
    { label: "column", value: "column" },
    { label: "row-reverse", value: "row-reverse" },
    { label: "column-reverse", value: "column-reverse" },
  ],
  position: [
    { label: "not selected", value: "" },
    { label: "static", value: "static" },
    { label: "relative", value: "relative" },
    { label: "fixed", value: "fixed" },
    { label: "absolute", value: "absolute" },
    { label: "sticky", value: "sticky" },
  ],
  textAlign: [
    { label: "not selected", value: "" },
    { label: "center", value: "center" },
    { label: "left", value: "left" },
    { label: "right", value: "right" },
    { label: "start", value: "start" },
    { label: "end", value: "end" },
    { label: "justify", value: "justify" },
  ],
  borderStyle: [
    { label: "not selected", value: "" },
    { label: "none", value: "none" },
    { label: "hidden", value: "hidden" },
    { label: "dotted", value: "dotted" },
    { label: "dashed", value: "dashed" },
    { label: "solid", value: "solid" },
    { label: "double", value: "double" },
    { label: "groove", value: "groove" },
    { label: "ridge", value: "ridge" },
    { label: "inset", value: "inset" },
    { label: "outset", value: "outset" },
  ],
  backgroundAttachment: [
    { label: "not selected", value: "" },
    { label: "scroll", value: "scroll" },
    { label: "fixed", value: "fixed" },
    { label: "local", value: "local" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
  backgroundClip: [
    { label: "not selected", value: "" },
    { label: "border-box", value: "border-box" },
    { label: "padding-box", value: "padding-box" },
    { label: "content-box", value: "content-box" },
    { label: "text", value: "text" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
  backgroundOrigin: [
    { label: "not selected", value: "" },
    { label: "border-box", value: "border-box" },
    { label: "padding-box", value: "padding-box" },
    { label: "content-box", value: "content-box" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
  backgroundRepeat: [
    { label: "not selected", value: "" },
    { label: "repeat", value: "repeat" },
    { label: "repeat-x", value: "repeat-x" },
    { label: "repeat-y", value: "repeat-y" },
    { label: "space", value: "space" },
    { label: "round", value: "round" },
    { label: "no-repeat", value: "no-repeat" },
    { label: "repeat space", value: "repeat space" },
    { label: "repeat repeat", value: "repeat repeat" },
    { label: "round space", value: "round space" },
    { label: "no-repeat round", value: "no-repeat round" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
  fontWeight: [
    { label: "not selected", value: "" },
    { label: "normal", value: "normal" },
    { label: "bold", value: "bold" },
    { label: "100", value: "100" },
    { label: "200", value: "200" },
    { label: "300", value: "300" },
    { label: "500", value: "500" },
    { label: "600", value: "600" },
    { label: "800", value: "800" },
    { label: "900", value: "900" },
    { label: "lighter", value: "lighter" },
    { label: "bolder", value: "bolder" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
};

export default options;
