const options = {
  display: [
    { label: "not selected", value: "" },
    { label: "block", value: "block" },
    { label: "flex", value: "flex" },
    { label: "inline", value: "inline" },
    { label: "none", value: "none" },
  ],
  flexWrap: [
    { label: "not selected", value: "" },
    { label: "nowrap", value: "nowrap" },
    { label: "wrap", value: "wrap" },
    { label: "wrap-reverse", value: "wrap-reverse" },
    { label: "inherit", value: "inherit" },
    { label: "initial", value: "initial" },
    { label: "revert", value: "revert" },
    { label: "revert-layer", value: "revert-layer" },
    { label: "unset", value: "unset" },
  ],
  flexDirection: [
    { label: "not selected", value: "" },
    { label: "row", value: "row" },
    { label: "column", value: "column" },
    { label: "row-reverse", value: "row-reverse" },
    { label: "column-reverse", value: "column-reverse" },
  ],
  position: [
    { label: "not selected", value: "" },
    { label: "static", value: "static" },
    { label: "relative", value: "relative" },
    // { label: "fixed", value: "fixed" },
    { label: "absolute", value: "absolute" },
    { label: "sticky", value: "sticky" },
  ],
  textAlign: [
    { label: "not selected", value: "" },
    { label: "center", value: "center" },
    { label: "left", value: "left" },
    { label: "right", value: "right" },
    { label: "start", value: "start" },
    { label: "end", value: "end" },
    { label: "justify", value: "justify" },
  ],
  borderStyle: [
    { label: "not selected", value: "" },
    { label: "none", value: "none" },
    { label: "hidden", value: "hidden" },
    { label: "dotted", value: "dotted" },
    { label: "dashed", value: "dashed" },
    { label: "solid", value: "solid" },
    { label: "double", value: "double" },
    { label: "groove", value: "groove" },
    { label: "ridge", value: "ridge" },
    { label: "inset", value: "inset" },
    { label: "outset", value: "outset" },
  ],
};

export default options;
